# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DesignWindow.ui'
#
# Created: Wed Oct 23 10:35:45 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PatientInfoDialog(object):
    def setupUi(self, PatientInfoDialog):
        PatientInfoDialog.setObjectName(_fromUtf8("PatientInfoDialog"))
        PatientInfoDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        PatientInfoDialog.resize(731, 620)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        PatientInfoDialog.setFont(font)
        PatientInfoDialog.setAcceptDrops(False)
        self.tabWidget = QtGui.QTabWidget(PatientInfoDialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(40, 20, 651, 511))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.widget = QtGui.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(80, 92, 491, 231))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.xingming_LineEdit = QtGui.QLineEdit(self.widget)
        self.xingming_LineEdit.setObjectName(_fromUtf8("xingming_LineEdit"))
        self.gridLayout.addWidget(self.xingming_LineEdit, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.xingbie_ComboBox = QtGui.QComboBox(self.widget)
        self.xingbie_ComboBox.setObjectName(_fromUtf8("xingbie_ComboBox"))
        self.xingbie_ComboBox.addItem(_fromUtf8(""))
        self.xingbie_ComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.xingbie_ComboBox, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.zhiye_LineEdit = QtGui.QLineEdit(self.widget)
        self.zhiye_LineEdit.setObjectName(_fromUtf8("zhiye_LineEdit"))
        self.gridLayout.addWidget(self.zhiye_LineEdit, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.minzu_LineEdit = QtGui.QLineEdit(self.widget)
        self.minzu_LineEdit.setObjectName(_fromUtf8("minzu_LineEdit"))
        self.gridLayout.addWidget(self.minzu_LineEdit, 1, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.jiatingzhuzhi_LineEdit = QtGui.QLineEdit(self.widget)
        self.jiatingzhuzhi_LineEdit.setObjectName(_fromUtf8("jiatingzhuzhi_LineEdit"))
        self.gridLayout_2.addWidget(self.jiatingzhuzhi_LineEdit, 0, 1, 1, 1)
        self.wenhuachengdu_ComboBox = QtGui.QComboBox(self.widget)
        self.wenhuachengdu_ComboBox.setObjectName(_fromUtf8("wenhuachengdu_ComboBox"))
        self.wenhuachengdu_ComboBox.addItem(_fromUtf8(""))
        self.wenhuachengdu_ComboBox.addItem(_fromUtf8(""))
        self.wenhuachengdu_ComboBox.addItem(_fromUtf8(""))
        self.wenhuachengdu_ComboBox.addItem(_fromUtf8(""))
        self.wenhuachengdu_ComboBox.addItem(_fromUtf8(""))
        self.wenhuachengdu_ComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.wenhuachengdu_ComboBox, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.line_8 = QtGui.QFrame(self.widget)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_3.addWidget(self.line_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.label_15 = QtGui.QLabel(self.widget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_9.addWidget(self.label_15)
        self.predict_value_label = QtGui.QLabel(self.widget)
        self.predict_value_label.setObjectName(_fromUtf8("predict_value_label"))
        self.horizontalLayout_9.addWidget(self.predict_value_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tab_2.setFont(font)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.layoutWidget = QtGui.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 40, 491, 429))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.zhongliubingshi_PlainTextEdit = QtGui.QPlainTextEdit(self.layoutWidget)
        self.zhongliubingshi_PlainTextEdit.setObjectName(_fromUtf8("zhongliubingshi_PlainTextEdit"))
        self.gridLayout_5.addWidget(self.zhongliubingshi_PlainTextEdit, 0, 2, 2, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.zhongliubingshi_ComboBox = QtGui.QComboBox(self.layoutWidget)
        self.zhongliubingshi_ComboBox.setObjectName(_fromUtf8("zhongliubingshi_ComboBox"))
        self.zhongliubingshi_ComboBox.addItem(_fromUtf8(""))
        self.zhongliubingshi_ComboBox.addItem(_fromUtf8(""))
        self.zhongliubingshi_ComboBox.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.zhongliubingshi_ComboBox, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem2, 2, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.layoutWidget)
        self.label_28.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_9.addWidget(self.label_28, 0, 0, 1, 1)
        self.feijiehebingshi_PlainTextEdit = QtGui.QPlainTextEdit(self.layoutWidget)
        self.feijiehebingshi_PlainTextEdit.setObjectName(_fromUtf8("feijiehebingshi_PlainTextEdit"))
        self.gridLayout_9.addWidget(self.feijiehebingshi_PlainTextEdit, 0, 2, 2, 1)
        self.feijihebingshi_ComboBox = QtGui.QComboBox(self.layoutWidget)
        self.feijihebingshi_ComboBox.setObjectName(_fromUtf8("feijihebingshi_ComboBox"))
        self.feijihebingshi_ComboBox.addItem(_fromUtf8(""))
        self.feijihebingshi_ComboBox.addItem(_fromUtf8(""))
        self.feijihebingshi_ComboBox.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.feijihebingshi_ComboBox, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_9)
        self.line_2 = QtGui.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout.addWidget(self.label_17)
        self.fenchenxirushi_ComboBox = QtGui.QComboBox(self.layoutWidget)
        self.fenchenxirushi_ComboBox.setObjectName(_fromUtf8("fenchenxirushi_ComboBox"))
        self.fenchenxirushi_ComboBox.addItem(_fromUtf8(""))
        self.fenchenxirushi_ComboBox.addItem(_fromUtf8(""))
        self.fenchenxirushi_ComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.fenchenxirushi_ComboBox)
        self.label_18 = QtGui.QLabel(self.layoutWidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout.addWidget(self.label_18)
        self.xirugongzuonianxian_LineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.xirugongzuonianxian_LineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.xirugongzuonianxian_LineEdit.setObjectName(_fromUtf8("xirugongzuonianxian_LineEdit"))
        self.horizontalLayout.addWidget(self.xirugongzuonianxian_LineEdit)
        self.label_19 = QtGui.QLabel(self.layoutWidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout.addWidget(self.label_19)
        self.label_20 = QtGui.QLabel(self.layoutWidget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout.addWidget(self.label_20)
        self.gongzhong_LineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.gongzhong_LineEdit.setObjectName(_fromUtf8("gongzhong_LineEdit"))
        self.horizontalLayout.addWidget(self.gongzhong_LineEdit)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_3 = QtGui.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem4, 2, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.layoutWidget)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_6.addWidget(self.label_21, 0, 0, 1, 1)
        self.yichuanbingshi_PlainTextEdit = QtGui.QPlainTextEdit(self.layoutWidget)
        self.yichuanbingshi_PlainTextEdit.setObjectName(_fromUtf8("yichuanbingshi_PlainTextEdit"))
        self.gridLayout_6.addWidget(self.yichuanbingshi_PlainTextEdit, 0, 2, 2, 1)
        self.yichuanbingshi_ComboBox = QtGui.QComboBox(self.layoutWidget)
        self.yichuanbingshi_ComboBox.setObjectName(_fromUtf8("yichuanbingshi_ComboBox"))
        self.yichuanbingshi_ComboBox.addItem(_fromUtf8(""))
        self.yichuanbingshi_ComboBox.addItem(_fromUtf8(""))
        self.yichuanbingshi_ComboBox.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.yichuanbingshi_ComboBox, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.line_4 = QtGui.QFrame(self.layoutWidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout.addWidget(self.line_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_22 = QtGui.QLabel(self.layoutWidget)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_2.addWidget(self.label_22)
        self.xiyanshi_ComboBox = QtGui.QComboBox(self.layoutWidget)
        self.xiyanshi_ComboBox.setObjectName(_fromUtf8("xiyanshi_ComboBox"))
        self.xiyanshi_ComboBox.addItem(_fromUtf8(""))
        self.xiyanshi_ComboBox.addItem(_fromUtf8(""))
        self.xiyanshi_ComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.xiyanshi_ComboBox)
        self.label_23 = QtGui.QLabel(self.layoutWidget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_2.addWidget(self.label_23)
        self.xiyannianxian_LineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.xiyannianxian_LineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.xiyannianxian_LineEdit.setObjectName(_fromUtf8("xiyannianxian_LineEdit"))
        self.horizontalLayout_2.addWidget(self.xiyannianxian_LineEdit)
        self.label_24 = QtGui.QLabel(self.layoutWidget)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_2.addWidget(self.label_24)
        self.label_25 = QtGui.QLabel(self.layoutWidget)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_2.addWidget(self.label_25)
        self.meitianxiyanshu_LineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.meitianxiyanshu_LineEdit.setMaximumSize(QtCore.QSize(30, 30))
        self.meitianxiyanshu_LineEdit.setObjectName(_fromUtf8("meitianxiyanshu_LineEdit"))
        self.horizontalLayout_2.addWidget(self.meitianxiyanshu_LineEdit)
        self.label_26 = QtGui.QLabel(self.layoutWidget)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_2.addWidget(self.label_26)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_5 = QtGui.QFrame(self.layoutWidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout.addWidget(self.line_5)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.huxibingshihuoqita_PlainTextEdit = QtGui.QPlainTextEdit(self.layoutWidget)
        self.huxibingshihuoqita_PlainTextEdit.setObjectName(_fromUtf8("huxibingshihuoqita_PlainTextEdit"))
        self.gridLayout_7.addWidget(self.huxibingshihuoqita_PlainTextEdit, 0, 2, 2, 1)
        self.huxibingshihuoqita_ComboBox = QtGui.QComboBox(self.layoutWidget)
        self.huxibingshihuoqita_ComboBox.setObjectName(_fromUtf8("huxibingshihuoqita_ComboBox"))
        self.huxibingshihuoqita_ComboBox.addItem(_fromUtf8(""))
        self.huxibingshihuoqita_ComboBox.addItem(_fromUtf8(""))
        self.huxibingshihuoqita_ComboBox.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.huxibingshihuoqita_ComboBox, 0, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.layoutWidget)
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_7.addWidget(self.label_27, 0, 0, 2, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.layoutWidget1 = QtGui.QWidget(self.tab_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(80, 40, 491, 421))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_12 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_32 = QtGui.QLabel(self.layoutWidget1)
        self.label_32.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_5.addWidget(self.label_32)
        self.linchuangzhenduanyijian_PlainTextEdit = QtGui.QPlainTextEdit(self.layoutWidget1)
        self.linchuangzhenduanyijian_PlainTextEdit.setObjectName(_fromUtf8("linchuangzhenduanyijian_PlainTextEdit"))
        self.horizontalLayout_5.addWidget(self.linchuangzhenduanyijian_PlainTextEdit)
        self.gridLayout_12.addLayout(self.horizontalLayout_5, 6, 0, 1, 2)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_37 = QtGui.QLabel(self.layoutWidget1)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_11.addWidget(self.label_37, 0, 0, 1, 2)
        self.label_38 = QtGui.QLabel(self.layoutWidget1)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_11.addWidget(self.label_38, 2, 0, 1, 2)
        self.label_39 = QtGui.QLabel(self.layoutWidget1)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_11.addWidget(self.label_39, 1, 0, 1, 2)
        self.kesou_wu_RadioButton = QtGui.QRadioButton(self.layoutWidget1)
        self.kesou_wu_RadioButton.setObjectName(_fromUtf8("kesou_wu_RadioButton"))
        self.gridLayout_11.addWidget(self.kesou_wu_RadioButton, 0, 2, 1, 2)
        self.xiongtong_wu_RadioButton = QtGui.QRadioButton(self.layoutWidget1)
        self.xiongtong_wu_RadioButton.setObjectName(_fromUtf8("xiongtong_wu_RadioButton"))
        self.gridLayout_11.addWidget(self.xiongtong_wu_RadioButton, 2, 2, 1, 2)
        self.xiongtong_you_RadioButton = QtGui.QRadioButton(self.layoutWidget1)
        self.xiongtong_you_RadioButton.setObjectName(_fromUtf8("xiongtong_you_RadioButton"))
        self.gridLayout_11.addWidget(self.xiongtong_you_RadioButton, 2, 4, 1, 1)
        self.kexue_you_RadioButton = QtGui.QRadioButton(self.layoutWidget1)
        self.kexue_you_RadioButton.setObjectName(_fromUtf8("kexue_you_RadioButton"))
        self.gridLayout_11.addWidget(self.kexue_you_RadioButton, 1, 4, 1, 1)
        self.kexue_wu_RadioButton = QtGui.QRadioButton(self.layoutWidget1)
        self.kexue_wu_RadioButton.setObjectName(_fromUtf8("kexue_wu_RadioButton"))
        self.gridLayout_11.addWidget(self.kexue_wu_RadioButton, 1, 2, 1, 2)
        self.kesou_you_RadioButton = QtGui.QRadioButton(self.layoutWidget1)
        self.kesou_you_RadioButton.setObjectName(_fromUtf8("kesou_you_RadioButton"))
        self.gridLayout_11.addWidget(self.kesou_you_RadioButton, 0, 4, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem6, 0, 5, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_29 = QtGui.QLabel(self.layoutWidget1)
        self.label_29.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_6.addWidget(self.label_29)
        self.zhusu_PlainTextEdit = QtGui.QPlainTextEdit(self.layoutWidget1)
        self.zhusu_PlainTextEdit.setObjectName(_fromUtf8("zhusu_PlainTextEdit"))
        self.horizontalLayout_6.addWidget(self.zhusu_PlainTextEdit)
        self.gridLayout_12.addLayout(self.horizontalLayout_6, 0, 0, 1, 2)
        self.fareHorizontalLayout = QtGui.QHBoxLayout()
        self.fareHorizontalLayout.setObjectName(_fromUtf8("fareHorizontalLayout"))
        self.label_30 = QtGui.QLabel(self.layoutWidget1)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.fareHorizontalLayout.addWidget(self.label_30)
        self.fare_wu_RadioButton = QtGui.QRadioButton(self.layoutWidget1)
        self.fare_wu_RadioButton.setObjectName(_fromUtf8("fare_wu_RadioButton"))
        self.fareHorizontalLayout.addWidget(self.fare_wu_RadioButton)
        self.fare_3738_RadioButton = QtGui.QRadioButton(self.layoutWidget1)
        self.fare_3738_RadioButton.setObjectName(_fromUtf8("fare_3738_RadioButton"))
        self.fareHorizontalLayout.addWidget(self.fare_3738_RadioButton)
        self.fare_38yishang_RadioButton = QtGui.QRadioButton(self.layoutWidget1)
        self.fare_38yishang_RadioButton.setObjectName(_fromUtf8("fare_38yishang_RadioButton"))
        self.fareHorizontalLayout.addWidget(self.fare_38yishang_RadioButton)
        self.gridLayout_12.addLayout(self.fareHorizontalLayout, 2, 0, 1, 1)
        self.line_6 = QtGui.QFrame(self.layoutWidget1)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_12.addWidget(self.line_6, 4, 0, 1, 2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_31 = QtGui.QLabel(self.layoutWidget1)
        self.label_31.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_4.addWidget(self.label_31)
        self.qitayuhuxiyouguan_PlainTextEdit = QtGui.QPlainTextEdit(self.layoutWidget1)
        self.qitayuhuxiyouguan_PlainTextEdit.setObjectName(_fromUtf8("qitayuhuxiyouguan_PlainTextEdit"))
        self.horizontalLayout_4.addWidget(self.qitayuhuxiyouguan_PlainTextEdit)
        self.gridLayout_12.addLayout(self.horizontalLayout_4, 5, 0, 1, 2)
        self.line_7 = QtGui.QFrame(self.layoutWidget1)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_12.addWidget(self.line_7, 1, 0, 1, 2)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.tanzhongdaixue_wu_RadioButton = QtGui.QRadioButton(self.layoutWidget1)
        self.tanzhongdaixue_wu_RadioButton.setObjectName(_fromUtf8("tanzhongdaixue_wu_RadioButton"))
        self.gridLayout_10.addWidget(self.tanzhongdaixue_wu_RadioButton, 0, 2, 1, 2)
        self.tanzhongdaixue_you_RadioButton = QtGui.QRadioButton(self.layoutWidget1)
        self.tanzhongdaixue_you_RadioButton.setObjectName(_fromUtf8("tanzhongdaixue_you_RadioButton"))
        self.gridLayout_10.addWidget(self.tanzhongdaixue_you_RadioButton, 0, 4, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem7, 0, 5, 1, 1)
        self.label_34 = QtGui.QLabel(self.layoutWidget1)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_10.addWidget(self.label_34, 0, 0, 1, 2)
        self.xiongmen_you_RadioButton = QtGui.QRadioButton(self.layoutWidget1)
        self.xiongmen_you_RadioButton.setObjectName(_fromUtf8("xiongmen_you_RadioButton"))
        self.gridLayout_10.addWidget(self.xiongmen_you_RadioButton, 1, 4, 1, 1)
        self.label_35 = QtGui.QLabel(self.layoutWidget1)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_10.addWidget(self.label_35, 1, 0, 1, 2)
        self.shengyinsiya_wu_RadioButton = QtGui.QRadioButton(self.layoutWidget1)
        self.shengyinsiya_wu_RadioButton.setObjectName(_fromUtf8("shengyinsiya_wu_RadioButton"))
        self.gridLayout_10.addWidget(self.shengyinsiya_wu_RadioButton, 2, 2, 1, 2)
        self.label_36 = QtGui.QLabel(self.layoutWidget1)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_10.addWidget(self.label_36, 2, 0, 1, 2)
        self.xiongmen_wu_RadioButton = QtGui.QRadioButton(self.layoutWidget1)
        self.xiongmen_wu_RadioButton.setObjectName(_fromUtf8("xiongmen_wu_RadioButton"))
        self.gridLayout_10.addWidget(self.xiongmen_wu_RadioButton, 1, 2, 1, 2)
        self.shengyinsiya_you_RadioButton = QtGui.QRadioButton(self.layoutWidget1)
        self.shengyinsiya_you_RadioButton.setObjectName(_fromUtf8("shengyinsiya_you_RadioButton"))
        self.gridLayout_10.addWidget(self.shengyinsiya_you_RadioButton, 2, 4, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_10, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setEnabled(True)
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.layoutWidget2 = QtGui.QWidget(self.tab_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(80, 40, 491, 421))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_11 = QtGui.QLabel(self.layoutWidget2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 1, 3, 1, 2)
        self.jiejiedaxiao_lineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.jiejiedaxiao_lineEdit.setObjectName(_fromUtf8("jiejiedaxiao_lineEdit"))
        self.gridLayout_3.addWidget(self.jiejiedaxiao_lineEdit, 1, 5, 1, 1)
        self.jianchariqi_dateEdit = QtGui.QDateEdit(self.layoutWidget2)
        self.jianchariqi_dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2013, 11, 2), QtCore.QTime(0, 0, 0)))
        self.jianchariqi_dateEdit.setCalendarPopup(True)
        self.jianchariqi_dateEdit.setObjectName(_fromUtf8("jianchariqi_dateEdit"))
        self.gridLayout_3.addWidget(self.jianchariqi_dateEdit, 1, 1, 1, 2)
        self.label_10 = QtGui.QLabel(self.layoutWidget2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.CThao_lineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.CThao_lineEdit.setObjectName(_fromUtf8("CThao_lineEdit"))
        self.gridLayout_3.addWidget(self.CThao_lineEdit, 0, 1, 1, 2)
        self.label_8 = QtGui.QLabel(self.layoutWidget2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 3, 1, 2)
        self.jianchafangshi_comboBox = QtGui.QComboBox(self.layoutWidget2)
        self.jianchafangshi_comboBox.setObjectName(_fromUtf8("jianchafangshi_comboBox"))
        self.jianchafangshi_comboBox.addItem(_fromUtf8(""))
        self.jianchafangshi_comboBox.addItem(_fromUtf8(""))
        self.jianchafangshi_comboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.jianchafangshi_comboBox, 0, 5, 1, 2)
        self.label_12 = QtGui.QLabel(self.layoutWidget2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 1, 6, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_13 = QtGui.QLabel(self.layoutWidget2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_3.addWidget(self.label_13)
        self.zuofeishangye_checkBox = QtGui.QCheckBox(self.layoutWidget2)
        self.zuofeishangye_checkBox.setObjectName(_fromUtf8("zuofeishangye_checkBox"))
        self.horizontalLayout_3.addWidget(self.zuofeishangye_checkBox)
        self.zuofeixiaye_checkBox = QtGui.QCheckBox(self.layoutWidget2)
        self.zuofeixiaye_checkBox.setObjectName(_fromUtf8("zuofeixiaye_checkBox"))
        self.horizontalLayout_3.addWidget(self.zuofeixiaye_checkBox)
        self.youfeishangye_checkBox = QtGui.QCheckBox(self.layoutWidget2)
        self.youfeishangye_checkBox.setObjectName(_fromUtf8("youfeishangye_checkBox"))
        self.horizontalLayout_3.addWidget(self.youfeishangye_checkBox)
        self.youfeizhongye_checkBox = QtGui.QCheckBox(self.layoutWidget2)
        self.youfeizhongye_checkBox.setObjectName(_fromUtf8("youfeizhongye_checkBox"))
        self.horizontalLayout_3.addWidget(self.youfeizhongye_checkBox)
        self.youfeixiaye_checkBox = QtGui.QCheckBox(self.layoutWidget2)
        self.youfeixiaye_checkBox.setObjectName(_fromUtf8("youfeixiaye_checkBox"))
        self.horizontalLayout_3.addWidget(self.youfeixiaye_checkBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_40 = QtGui.QLabel(self.layoutWidget2)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_4.addWidget(self.label_40, 0, 0, 1, 1)
        self.linbajiezhong_wu_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.linbajiezhong_wu_RadioButton.setObjectName(_fromUtf8("linbajiezhong_wu_RadioButton"))
        self.gridLayout_4.addWidget(self.linbajiezhong_wu_RadioButton, 0, 2, 1, 1)
        self.label_41 = QtGui.QLabel(self.layoutWidget2)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_4.addWidget(self.label_41, 1, 0, 1, 1)
        self.maobolimi_wu_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.maobolimi_wu_RadioButton.setObjectName(_fromUtf8("maobolimi_wu_RadioButton"))
        self.gridLayout_4.addWidget(self.maobolimi_wu_RadioButton, 1, 2, 1, 1)
        self.linbajiezhong_you_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.linbajiezhong_you_RadioButton.setObjectName(_fromUtf8("linbajiezhong_you_RadioButton"))
        self.gridLayout_4.addWidget(self.linbajiezhong_you_RadioButton, 0, 3, 1, 1)
        self.label_44 = QtGui.QLabel(self.layoutWidget2)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_4.addWidget(self.label_44, 4, 0, 1, 1)
        self.kongdong_wu_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.kongdong_wu_RadioButton.setObjectName(_fromUtf8("kongdong_wu_RadioButton"))
        self.gridLayout_4.addWidget(self.kongdong_wu_RadioButton, 4, 2, 1, 1)
        self.label_45 = QtGui.QLabel(self.layoutWidget2)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_4.addWidget(self.label_45, 5, 0, 1, 1)
        self.kongdong_you_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.kongdong_you_RadioButton.setObjectName(_fromUtf8("kongdong_you_RadioButton"))
        self.gridLayout_4.addWidget(self.kongdong_you_RadioButton, 4, 3, 1, 1)
        self.xiongshui_you_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.xiongshui_you_RadioButton.setObjectName(_fromUtf8("xiongshui_you_RadioButton"))
        self.gridLayout_4.addWidget(self.xiongshui_you_RadioButton, 5, 3, 1, 1)
        self.xiongshui_wu_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.xiongshui_wu_RadioButton.setObjectName(_fromUtf8("xiongshui_wu_RadioButton"))
        self.gridLayout_4.addWidget(self.xiongshui_wu_RadioButton, 5, 2, 1, 1)
        self.label_42 = QtGui.QLabel(self.layoutWidget2)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_4.addWidget(self.label_42, 2, 0, 1, 1)
        self.maobolimi_shi_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.maobolimi_shi_RadioButton.setObjectName(_fromUtf8("maobolimi_shi_RadioButton"))
        self.gridLayout_4.addWidget(self.maobolimi_shi_RadioButton, 1, 3, 1, 1)
        self.jiejiebianyuan_guanghua_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.jiejiebianyuan_guanghua_RadioButton.setObjectName(_fromUtf8("jiejiebianyuan_guanghua_RadioButton"))
        self.gridLayout_4.addWidget(self.jiejiebianyuan_guanghua_RadioButton, 2, 2, 1, 1)
        self.jiejiebianyuan_maocao_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.jiejiebianyuan_maocao_RadioButton.setObjectName(_fromUtf8("jiejiebianyuan_maocao_RadioButton"))
        self.gridLayout_4.addWidget(self.jiejiebianyuan_maocao_RadioButton, 2, 3, 1, 1)
        self.label_43 = QtGui.QLabel(self.layoutWidget2)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_4.addWidget(self.label_43, 3, 0, 1, 1)
        self.jiejiekongpao_wu_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.jiejiekongpao_wu_RadioButton.setObjectName(_fromUtf8("jiejiekongpao_wu_RadioButton"))
        self.gridLayout_4.addWidget(self.jiejiekongpao_wu_RadioButton, 3, 2, 1, 1)
        self.jiejiekongpao_you_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.jiejiekongpao_you_RadioButton.setObjectName(_fromUtf8("jiejiekongpao_you_RadioButton"))
        self.gridLayout_4.addWidget(self.jiejiekongpao_you_RadioButton, 3, 3, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 1, 1, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout_4)
        spacerItem11 = QtGui.QSpacerItem(98, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.jiejiegaihua_wu_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.jiejiegaihua_wu_RadioButton.setObjectName(_fromUtf8("jiejiegaihua_wu_RadioButton"))
        self.gridLayout_8.addWidget(self.jiejiegaihua_wu_RadioButton, 4, 2, 1, 1)
        self.xiongmoaoxian_you_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.xiongmoaoxian_you_RadioButton.setObjectName(_fromUtf8("xiongmoaoxian_you_RadioButton"))
        self.gridLayout_8.addWidget(self.xiongmoaoxian_you_RadioButton, 5, 3, 1, 1)
        self.label_51 = QtGui.QLabel(self.layoutWidget2)
        self.label_51.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_8.addWidget(self.label_51, 5, 0, 1, 1)
        self.jiejiegaihua_you_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.jiejiegaihua_you_RadioButton.setObjectName(_fromUtf8("jiejiegaihua_you_RadioButton"))
        self.gridLayout_8.addWidget(self.jiejiegaihua_you_RadioButton, 4, 3, 1, 1)
        self.xiongmoaoxian_wuu_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.xiongmoaoxian_wuu_RadioButton.setObjectName(_fromUtf8("xiongmoaoxian_wuu_RadioButton"))
        self.gridLayout_8.addWidget(self.xiongmoaoxian_wuu_RadioButton, 5, 2, 1, 1)
        self.label_46 = QtGui.QLabel(self.layoutWidget2)
        self.label_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_8.addWidget(self.label_46, 0, 0, 1, 1)
        self.jiejiemidu_junyun_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.jiejiemidu_junyun_RadioButton.setObjectName(_fromUtf8("jiejiemidu_junyun_RadioButton"))
        self.gridLayout_8.addWidget(self.jiejiemidu_junyun_RadioButton, 0, 2, 1, 1)
        self.jiejiemidu_bujunyun_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.jiejiemidu_bujunyun_RadioButton.setObjectName(_fromUtf8("jiejiemidu_bujunyun_RadioButton"))
        self.gridLayout_8.addWidget(self.jiejiemidu_bujunyun_RadioButton, 0, 3, 1, 1)
        self.label_47 = QtGui.QLabel(self.layoutWidget2)
        self.label_47.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_8.addWidget(self.label_47, 1, 0, 1, 1)
        self.shixingjiejie_shi_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.shixingjiejie_shi_RadioButton.setObjectName(_fromUtf8("shixingjiejie_shi_RadioButton"))
        self.gridLayout_8.addWidget(self.shixingjiejie_shi_RadioButton, 1, 3, 1, 1)
        self.shixingjiejie_wu_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.shixingjiejie_wu_RadioButton.setObjectName(_fromUtf8("shixingjiejie_wu_RadioButton"))
        self.gridLayout_8.addWidget(self.shixingjiejie_wu_RadioButton, 1, 2, 1, 1)
        self.label_48 = QtGui.QLabel(self.layoutWidget2)
        self.label_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_8.addWidget(self.label_48, 2, 0, 1, 1)
        self.youyunzheng_wu_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.youyunzheng_wu_RadioButton.setObjectName(_fromUtf8("youyunzheng_wu_RadioButton"))
        self.gridLayout_8.addWidget(self.youyunzheng_wu_RadioButton, 2, 2, 1, 1)
        self.label_49 = QtGui.QLabel(self.layoutWidget2)
        self.label_49.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_8.addWidget(self.label_49, 3, 0, 1, 1)
        self.jiejiefenye_wu_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.jiejiefenye_wu_RadioButton.setObjectName(_fromUtf8("jiejiefenye_wu_RadioButton"))
        self.gridLayout_8.addWidget(self.jiejiefenye_wu_RadioButton, 3, 2, 1, 1)
        self.youyunzheng_you_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.youyunzheng_you_RadioButton.setObjectName(_fromUtf8("youyunzheng_you_RadioButton"))
        self.gridLayout_8.addWidget(self.youyunzheng_you_RadioButton, 2, 3, 1, 1)
        self.jiejiefenye_you_RadioButton = QtGui.QRadioButton(self.layoutWidget2)
        self.jiejiefenye_you_RadioButton.setObjectName(_fromUtf8("jiejiefenye_you_RadioButton"))
        self.gridLayout_8.addWidget(self.jiejiefenye_you_RadioButton, 3, 3, 1, 1)
        self.label_50 = QtGui.QLabel(self.layoutWidget2)
        self.label_50.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_8.addWidget(self.label_50, 4, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem12, 2, 1, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem13)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_14 = QtGui.QLabel(self.layoutWidget2)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_7.addWidget(self.label_14)
        self.CTzhenduan_plainTextEdit = QtGui.QPlainTextEdit(self.layoutWidget2)
        self.CTzhenduan_plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.CTzhenduan_plainTextEdit.setObjectName(_fromUtf8("CTzhenduan_plainTextEdit"))
        self.horizontalLayout_7.addWidget(self.CTzhenduan_plainTextEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.acceptButton = QtGui.QPushButton(PatientInfoDialog)
        self.acceptButton.setGeometry(QtCore.QRect(40, 550, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.acceptButton.setFont(font)
        self.acceptButton.setAutoFillBackground(False)
        self.acceptButton.setObjectName(_fromUtf8("acceptButton"))
        self.cancelButton = QtGui.QPushButton(PatientInfoDialog)
        self.cancelButton.setGeometry(QtCore.QRect(370, 550, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.label.setBuddy(self.xingming_LineEdit)
        self.label_5.setBuddy(self.xingbie_ComboBox)
        self.label_2.setBuddy(self.zhiye_LineEdit)
        self.label_3.setBuddy(self.minzu_LineEdit)
        self.label_4.setBuddy(self.jiatingzhuzhi_LineEdit)
        self.label_6.setBuddy(self.wenhuachengdu_ComboBox)

        self.retranslateUi(PatientInfoDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL(_fromUtf8("clicked()")), PatientInfoDialog.reject)
        QtCore.QObject.connect(self.acceptButton, QtCore.SIGNAL(_fromUtf8("clicked()")), PatientInfoDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(PatientInfoDialog)
        PatientInfoDialog.setTabOrder(self.xingming_LineEdit, self.xingbie_ComboBox)
        PatientInfoDialog.setTabOrder(self.xingbie_ComboBox, self.zhiye_LineEdit)
        PatientInfoDialog.setTabOrder(self.zhiye_LineEdit, self.minzu_LineEdit)
        PatientInfoDialog.setTabOrder(self.minzu_LineEdit, self.jiatingzhuzhi_LineEdit)
        PatientInfoDialog.setTabOrder(self.jiatingzhuzhi_LineEdit, self.wenhuachengdu_ComboBox)
        PatientInfoDialog.setTabOrder(self.wenhuachengdu_ComboBox, self.zhongliubingshi_ComboBox)
        PatientInfoDialog.setTabOrder(self.zhongliubingshi_ComboBox, self.zhongliubingshi_PlainTextEdit)
        PatientInfoDialog.setTabOrder(self.zhongliubingshi_PlainTextEdit, self.feijihebingshi_ComboBox)
        PatientInfoDialog.setTabOrder(self.feijihebingshi_ComboBox, self.feijiehebingshi_PlainTextEdit)
        PatientInfoDialog.setTabOrder(self.feijiehebingshi_PlainTextEdit, self.fenchenxirushi_ComboBox)
        PatientInfoDialog.setTabOrder(self.fenchenxirushi_ComboBox, self.xirugongzuonianxian_LineEdit)
        PatientInfoDialog.setTabOrder(self.xirugongzuonianxian_LineEdit, self.gongzhong_LineEdit)
        PatientInfoDialog.setTabOrder(self.gongzhong_LineEdit, self.yichuanbingshi_ComboBox)
        PatientInfoDialog.setTabOrder(self.yichuanbingshi_ComboBox, self.yichuanbingshi_PlainTextEdit)
        PatientInfoDialog.setTabOrder(self.yichuanbingshi_PlainTextEdit, self.xiyanshi_ComboBox)
        PatientInfoDialog.setTabOrder(self.xiyanshi_ComboBox, self.xiyannianxian_LineEdit)
        PatientInfoDialog.setTabOrder(self.xiyannianxian_LineEdit, self.meitianxiyanshu_LineEdit)
        PatientInfoDialog.setTabOrder(self.meitianxiyanshu_LineEdit, self.huxibingshihuoqita_ComboBox)
        PatientInfoDialog.setTabOrder(self.huxibingshihuoqita_ComboBox, self.huxibingshihuoqita_PlainTextEdit)
        PatientInfoDialog.setTabOrder(self.huxibingshihuoqita_PlainTextEdit, self.zhusu_PlainTextEdit)
        PatientInfoDialog.setTabOrder(self.zhusu_PlainTextEdit, self.fare_wu_RadioButton)
        PatientInfoDialog.setTabOrder(self.fare_wu_RadioButton, self.fare_3738_RadioButton)
        PatientInfoDialog.setTabOrder(self.fare_3738_RadioButton, self.fare_38yishang_RadioButton)
        PatientInfoDialog.setTabOrder(self.fare_38yishang_RadioButton, self.kesou_wu_RadioButton)
        PatientInfoDialog.setTabOrder(self.kesou_wu_RadioButton, self.kesou_you_RadioButton)
        PatientInfoDialog.setTabOrder(self.kesou_you_RadioButton, self.tanzhongdaixue_wu_RadioButton)
        PatientInfoDialog.setTabOrder(self.tanzhongdaixue_wu_RadioButton, self.tanzhongdaixue_you_RadioButton)
        PatientInfoDialog.setTabOrder(self.tanzhongdaixue_you_RadioButton, self.kexue_wu_RadioButton)
        PatientInfoDialog.setTabOrder(self.kexue_wu_RadioButton, self.kexue_you_RadioButton)
        PatientInfoDialog.setTabOrder(self.kexue_you_RadioButton, self.xiongmen_wu_RadioButton)
        PatientInfoDialog.setTabOrder(self.xiongmen_wu_RadioButton, self.xiongmen_you_RadioButton)
        PatientInfoDialog.setTabOrder(self.xiongmen_you_RadioButton, self.xiongtong_wu_RadioButton)
        PatientInfoDialog.setTabOrder(self.xiongtong_wu_RadioButton, self.xiongtong_you_RadioButton)
        PatientInfoDialog.setTabOrder(self.xiongtong_you_RadioButton, self.shengyinsiya_wu_RadioButton)
        PatientInfoDialog.setTabOrder(self.shengyinsiya_wu_RadioButton, self.shengyinsiya_you_RadioButton)
        PatientInfoDialog.setTabOrder(self.shengyinsiya_you_RadioButton, self.qitayuhuxiyouguan_PlainTextEdit)
        PatientInfoDialog.setTabOrder(self.qitayuhuxiyouguan_PlainTextEdit, self.linchuangzhenduanyijian_PlainTextEdit)
        PatientInfoDialog.setTabOrder(self.linchuangzhenduanyijian_PlainTextEdit, self.CThao_lineEdit)
        PatientInfoDialog.setTabOrder(self.CThao_lineEdit, self.jianchafangshi_comboBox)
        PatientInfoDialog.setTabOrder(self.jianchafangshi_comboBox, self.jianchariqi_dateEdit)
        PatientInfoDialog.setTabOrder(self.jianchariqi_dateEdit, self.jiejiedaxiao_lineEdit)
        PatientInfoDialog.setTabOrder(self.jiejiedaxiao_lineEdit, self.zuofeishangye_checkBox)
        PatientInfoDialog.setTabOrder(self.zuofeishangye_checkBox, self.zuofeixiaye_checkBox)
        PatientInfoDialog.setTabOrder(self.zuofeixiaye_checkBox, self.youfeishangye_checkBox)
        PatientInfoDialog.setTabOrder(self.youfeishangye_checkBox, self.youfeizhongye_checkBox)
        PatientInfoDialog.setTabOrder(self.youfeizhongye_checkBox, self.youfeixiaye_checkBox)
        PatientInfoDialog.setTabOrder(self.youfeixiaye_checkBox, self.linbajiezhong_wu_RadioButton)
        PatientInfoDialog.setTabOrder(self.linbajiezhong_wu_RadioButton, self.linbajiezhong_you_RadioButton)
        PatientInfoDialog.setTabOrder(self.linbajiezhong_you_RadioButton, self.maobolimi_wu_RadioButton)
        PatientInfoDialog.setTabOrder(self.maobolimi_wu_RadioButton, self.maobolimi_shi_RadioButton)
        PatientInfoDialog.setTabOrder(self.maobolimi_shi_RadioButton, self.jiejiebianyuan_guanghua_RadioButton)
        PatientInfoDialog.setTabOrder(self.jiejiebianyuan_guanghua_RadioButton, self.jiejiebianyuan_maocao_RadioButton)
        PatientInfoDialog.setTabOrder(self.jiejiebianyuan_maocao_RadioButton, self.jiejiekongpao_wu_RadioButton)
        PatientInfoDialog.setTabOrder(self.jiejiekongpao_wu_RadioButton, self.jiejiekongpao_you_RadioButton)
        PatientInfoDialog.setTabOrder(self.jiejiekongpao_you_RadioButton, self.kongdong_wu_RadioButton)
        PatientInfoDialog.setTabOrder(self.kongdong_wu_RadioButton, self.kongdong_you_RadioButton)
        PatientInfoDialog.setTabOrder(self.kongdong_you_RadioButton, self.xiongshui_wu_RadioButton)
        PatientInfoDialog.setTabOrder(self.xiongshui_wu_RadioButton, self.xiongshui_you_RadioButton)
        PatientInfoDialog.setTabOrder(self.xiongshui_you_RadioButton, self.jiejiemidu_junyun_RadioButton)
        PatientInfoDialog.setTabOrder(self.jiejiemidu_junyun_RadioButton, self.jiejiemidu_bujunyun_RadioButton)
        PatientInfoDialog.setTabOrder(self.jiejiemidu_bujunyun_RadioButton, self.shixingjiejie_wu_RadioButton)
        PatientInfoDialog.setTabOrder(self.shixingjiejie_wu_RadioButton, self.shixingjiejie_shi_RadioButton)
        PatientInfoDialog.setTabOrder(self.shixingjiejie_shi_RadioButton, self.youyunzheng_wu_RadioButton)
        PatientInfoDialog.setTabOrder(self.youyunzheng_wu_RadioButton, self.youyunzheng_you_RadioButton)
        PatientInfoDialog.setTabOrder(self.youyunzheng_you_RadioButton, self.jiejiefenye_wu_RadioButton)
        PatientInfoDialog.setTabOrder(self.jiejiefenye_wu_RadioButton, self.jiejiefenye_you_RadioButton)
        PatientInfoDialog.setTabOrder(self.jiejiefenye_you_RadioButton, self.jiejiegaihua_wu_RadioButton)
        PatientInfoDialog.setTabOrder(self.jiejiegaihua_wu_RadioButton, self.jiejiegaihua_you_RadioButton)
        PatientInfoDialog.setTabOrder(self.jiejiegaihua_you_RadioButton, self.xiongmoaoxian_wuu_RadioButton)
        PatientInfoDialog.setTabOrder(self.xiongmoaoxian_wuu_RadioButton, self.xiongmoaoxian_you_RadioButton)
        PatientInfoDialog.setTabOrder(self.xiongmoaoxian_you_RadioButton, self.CTzhenduan_plainTextEdit)
        PatientInfoDialog.setTabOrder(self.CTzhenduan_plainTextEdit, self.acceptButton)
        PatientInfoDialog.setTabOrder(self.acceptButton, self.cancelButton)
        PatientInfoDialog.setTabOrder(self.cancelButton, self.tabWidget)

    def retranslateUi(self, PatientInfoDialog):
        PatientInfoDialog.setWindowTitle(_translate("PatientInfoDialog", "患者信息", None))
        self.label.setText(_translate("PatientInfoDialog", "姓名", None))
        self.label_5.setText(_translate("PatientInfoDialog", "性别", None))
        self.xingbie_ComboBox.setItemText(0, _translate("PatientInfoDialog", "男", None))
        self.xingbie_ComboBox.setItemText(1, _translate("PatientInfoDialog", "女", None))
        self.label_2.setText(_translate("PatientInfoDialog", "职业", None))
        self.label_3.setText(_translate("PatientInfoDialog", "民族", None))
        self.wenhuachengdu_ComboBox.setItemText(0, _translate("PatientInfoDialog", "大学以上", None))
        self.wenhuachengdu_ComboBox.setItemText(1, _translate("PatientInfoDialog", "大学", None))
        self.wenhuachengdu_ComboBox.setItemText(2, _translate("PatientInfoDialog", "高中", None))
        self.wenhuachengdu_ComboBox.setItemText(3, _translate("PatientInfoDialog", "初中", None))
        self.wenhuachengdu_ComboBox.setItemText(4, _translate("PatientInfoDialog", "小学", None))
        self.wenhuachengdu_ComboBox.setItemText(5, _translate("PatientInfoDialog", "文盲或半文盲", None))
        self.label_4.setText(_translate("PatientInfoDialog", "家庭住址", None))
        self.label_6.setText(_translate("PatientInfoDialog", "文化程度", None))
        self.label_15.setText(_translate("PatientInfoDialog", "辅助诊断预测结果：", None))
        self.predict_value_label.setText(_translate("PatientInfoDialog", "暂无", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PatientInfoDialog", "个人信息", None))
        self.label_7.setText(_translate("PatientInfoDialog", "肿 瘤 病 史", None))
        self.zhongliubingshi_ComboBox.setItemText(0, _translate("PatientInfoDialog", "无", None))
        self.zhongliubingshi_ComboBox.setItemText(1, _translate("PatientInfoDialog", "有", None))
        self.zhongliubingshi_ComboBox.setItemText(2, _translate("PatientInfoDialog", "不详", None))
        self.label_28.setText(_translate("PatientInfoDialog", "肺结核病史", None))
        self.feijihebingshi_ComboBox.setItemText(0, _translate("PatientInfoDialog", "无", None))
        self.feijihebingshi_ComboBox.setItemText(1, _translate("PatientInfoDialog", "有", None))
        self.feijihebingshi_ComboBox.setItemText(2, _translate("PatientInfoDialog", "不详", None))
        self.label_17.setText(_translate("PatientInfoDialog", "粉尘吸入史", None))
        self.fenchenxirushi_ComboBox.setItemText(0, _translate("PatientInfoDialog", "无", None))
        self.fenchenxirushi_ComboBox.setItemText(1, _translate("PatientInfoDialog", "有", None))
        self.fenchenxirushi_ComboBox.setItemText(2, _translate("PatientInfoDialog", "不详", None))
        self.label_18.setText(_translate("PatientInfoDialog", "吸入工作年限", None))
        self.label_19.setText(_translate("PatientInfoDialog", "年   ", None))
        self.label_20.setText(_translate("PatientInfoDialog", "工种：", None))
        self.label_21.setText(_translate("PatientInfoDialog", "遗 传 病 史", None))
        self.yichuanbingshi_ComboBox.setItemText(0, _translate("PatientInfoDialog", "无", None))
        self.yichuanbingshi_ComboBox.setItemText(1, _translate("PatientInfoDialog", "有", None))
        self.yichuanbingshi_ComboBox.setItemText(2, _translate("PatientInfoDialog", "不详", None))
        self.label_22.setText(_translate("PatientInfoDialog", "吸 烟 史    ", None))
        self.xiyanshi_ComboBox.setItemText(0, _translate("PatientInfoDialog", "无", None))
        self.xiyanshi_ComboBox.setItemText(1, _translate("PatientInfoDialog", "有", None))
        self.xiyanshi_ComboBox.setItemText(2, _translate("PatientInfoDialog", "不详", None))
        self.label_23.setText(_translate("PatientInfoDialog", "吸烟年限", None))
        self.label_24.setText(_translate("PatientInfoDialog", "年    ", None))
        self.label_25.setText(_translate("PatientInfoDialog", "每天吸烟数", None))
        self.label_26.setText(_translate("PatientInfoDialog", "支", None))
        self.huxibingshihuoqita_ComboBox.setItemText(0, _translate("PatientInfoDialog", "无", None))
        self.huxibingshihuoqita_ComboBox.setItemText(1, _translate("PatientInfoDialog", "有", None))
        self.huxibingshihuoqita_ComboBox.setItemText(2, _translate("PatientInfoDialog", "不详", None))
        self.label_27.setText(_translate("PatientInfoDialog", "呼 吸 病 史\n"
"或 其 他  ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("PatientInfoDialog", "既往史", None))
        self.label_32.setText(_translate("PatientInfoDialog", "临床诊断意见：", None))
        self.label_37.setText(_translate("PatientInfoDialog", "咳嗽", None))
        self.label_38.setText(_translate("PatientInfoDialog", "胸痛", None))
        self.label_39.setText(_translate("PatientInfoDialog", "咳血", None))
        self.kesou_wu_RadioButton.setText(_translate("PatientInfoDialog", "无", None))
        self.xiongtong_wu_RadioButton.setText(_translate("PatientInfoDialog", "无", None))
        self.xiongtong_you_RadioButton.setText(_translate("PatientInfoDialog", "有", None))
        self.kexue_you_RadioButton.setText(_translate("PatientInfoDialog", "有", None))
        self.kexue_wu_RadioButton.setText(_translate("PatientInfoDialog", "无", None))
        self.kesou_you_RadioButton.setText(_translate("PatientInfoDialog", "有", None))
        self.label_29.setText(_translate("PatientInfoDialog", "主诉：", None))
        self.label_30.setText(_translate("PatientInfoDialog", "发热", None))
        self.fare_wu_RadioButton.setText(_translate("PatientInfoDialog", "无", None))
        self.fare_3738_RadioButton.setText(_translate("PatientInfoDialog", "37.5-38摄氏度", None))
        self.fare_38yishang_RadioButton.setText(_translate("PatientInfoDialog", "38摄氏度以上", None))
        self.label_31.setText(_translate("PatientInfoDialog", "其它与呼吸有关\n"
"的临床表现：", None))
        self.tanzhongdaixue_wu_RadioButton.setText(_translate("PatientInfoDialog", "无", None))
        self.tanzhongdaixue_you_RadioButton.setText(_translate("PatientInfoDialog", "有", None))
        self.label_34.setText(_translate("PatientInfoDialog", "痰中带血", None))
        self.xiongmen_you_RadioButton.setText(_translate("PatientInfoDialog", "有", None))
        self.label_35.setText(_translate("PatientInfoDialog", "胸闷", None))
        self.shengyinsiya_wu_RadioButton.setText(_translate("PatientInfoDialog", "无", None))
        self.label_36.setText(_translate("PatientInfoDialog", "声音嘶哑", None))
        self.xiongmen_wu_RadioButton.setText(_translate("PatientInfoDialog", "无", None))
        self.shengyinsiya_you_RadioButton.setText(_translate("PatientInfoDialog", "有", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("PatientInfoDialog", "就诊信息", None))
        self.label_11.setText(_translate("PatientInfoDialog", "结节大小", None))
        self.label_10.setText(_translate("PatientInfoDialog", "检查日期", None))
        self.label_8.setText(_translate("PatientInfoDialog", "CT号", None))
        self.label_9.setText(_translate("PatientInfoDialog", "检查方式", None))
        self.jianchafangshi_comboBox.setItemText(0, _translate("PatientInfoDialog", "平扫", None))
        self.jianchafangshi_comboBox.setItemText(1, _translate("PatientInfoDialog", "增强扫描", None))
        self.jianchafangshi_comboBox.setItemText(2, _translate("PatientInfoDialog", "其他", None))
        self.label_12.setText(_translate("PatientInfoDialog", "厘米", None))
        self.label_13.setText(_translate("PatientInfoDialog", "节点部位", None))
        self.zuofeishangye_checkBox.setText(_translate("PatientInfoDialog", "左肺上叶", None))
        self.zuofeixiaye_checkBox.setText(_translate("PatientInfoDialog", "左肺下叶", None))
        self.youfeishangye_checkBox.setText(_translate("PatientInfoDialog", "右肺上叶", None))
        self.youfeizhongye_checkBox.setText(_translate("PatientInfoDialog", "右肺中叶", None))
        self.youfeixiaye_checkBox.setText(_translate("PatientInfoDialog", "右肺下叶", None))
        self.label_40.setText(_translate("PatientInfoDialog", "淋巴结肿", None))
        self.linbajiezhong_wu_RadioButton.setText(_translate("PatientInfoDialog", "无", None))
        self.label_41.setText(_translate("PatientInfoDialog", "毛玻璃密", None))
        self.maobolimi_wu_RadioButton.setText(_translate("PatientInfoDialog", "无", None))
        self.linbajiezhong_you_RadioButton.setText(_translate("PatientInfoDialog", "有", None))
        self.label_44.setText(_translate("PatientInfoDialog", "空洞", None))
        self.kongdong_wu_RadioButton.setText(_translate("PatientInfoDialog", "无", None))
        self.label_45.setText(_translate("PatientInfoDialog", "胸水", None))
        self.kongdong_you_RadioButton.setText(_translate("PatientInfoDialog", "有", None))
        self.xiongshui_you_RadioButton.setText(_translate("PatientInfoDialog", "有", None))
        self.xiongshui_wu_RadioButton.setText(_translate("PatientInfoDialog", "无", None))
        self.label_42.setText(_translate("PatientInfoDialog", "结节边缘", None))
        self.maobolimi_shi_RadioButton.setText(_translate("PatientInfoDialog", "是", None))
        self.jiejiebianyuan_guanghua_RadioButton.setText(_translate("PatientInfoDialog", "光滑", None))
        self.jiejiebianyuan_maocao_RadioButton.setText(_translate("PatientInfoDialog", "毛糙", None))
        self.label_43.setText(_translate("PatientInfoDialog", "结节空泡", None))
        self.jiejiekongpao_wu_RadioButton.setText(_translate("PatientInfoDialog", "无", None))
        self.jiejiekongpao_you_RadioButton.setText(_translate("PatientInfoDialog", "有", None))
        self.jiejiegaihua_wu_RadioButton.setText(_translate("PatientInfoDialog", "无", None))
        self.xiongmoaoxian_you_RadioButton.setText(_translate("PatientInfoDialog", "有", None))
        self.label_51.setText(_translate("PatientInfoDialog", "胸膜凹陷", None))
        self.jiejiegaihua_you_RadioButton.setText(_translate("PatientInfoDialog", "有", None))
        self.xiongmoaoxian_wuu_RadioButton.setText(_translate("PatientInfoDialog", "无", None))
        self.label_46.setText(_translate("PatientInfoDialog", "结节密度", None))
        self.jiejiemidu_junyun_RadioButton.setText(_translate("PatientInfoDialog", "均匀", None))
        self.jiejiemidu_bujunyun_RadioButton.setText(_translate("PatientInfoDialog", "不均匀", None))
        self.label_47.setText(_translate("PatientInfoDialog", "实性结节", None))
        self.shixingjiejie_shi_RadioButton.setText(_translate("PatientInfoDialog", "是", None))
        self.shixingjiejie_wu_RadioButton.setText(_translate("PatientInfoDialog", "无", None))
        self.label_48.setText(_translate("PatientInfoDialog", "有晕征", None))
        self.youyunzheng_wu_RadioButton.setText(_translate("PatientInfoDialog", "无", None))
        self.label_49.setText(_translate("PatientInfoDialog", "结节分叶", None))
        self.jiejiefenye_wu_RadioButton.setText(_translate("PatientInfoDialog", "无", None))
        self.youyunzheng_you_RadioButton.setText(_translate("PatientInfoDialog", "有", None))
        self.jiejiefenye_you_RadioButton.setText(_translate("PatientInfoDialog", "有", None))
        self.label_50.setText(_translate("PatientInfoDialog", "结节钙化", None))
        self.label_14.setText(_translate("PatientInfoDialog", "CT诊断：", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("PatientInfoDialog", "影像查看结果", None))
        self.acceptButton.setText(_translate("PatientInfoDialog", "确定", None))
        self.cancelButton.setText(_translate("PatientInfoDialog", "取消", None))

