# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DesignWindow.ui'
#
# Created: Tue Oct 08 10:18:05 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PatientInfoDialog(object):
    def setupUi(self, PatientInfoDialog):
        PatientInfoDialog.setObjectName(_fromUtf8("PatientInfoDialog"))
        PatientInfoDialog.resize(640, 480)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        PatientInfoDialog.setFont(font)
        PatientInfoDialog.setAcceptDrops(False)
        self.buttonBox = QtGui.QDialogButtonBox(PatientInfoDialog)
        self.buttonBox.setGeometry(QtCore.QRect(390, 420, 201, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tabWidget = QtGui.QTabWidget(PatientInfoDialog)
        self.tabWidget.setGeometry(QtCore.QRect(60, 30, 531, 381))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setGeometry(QtCore.QRect(40, 50, 431, 231))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.name_lineEdit = QtGui.QLineEdit(self.widget)
        self.name_lineEdit.setObjectName(_fromUtf8("name_lineEdit"))
        self.gridLayout.addWidget(self.name_lineEdit, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.comboBox = QtGui.QComboBox(self.widget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.job_lineEdit = QtGui.QLineEdit(self.widget)
        self.job_lineEdit.setObjectName(_fromUtf8("job_lineEdit"))
        self.gridLayout.addWidget(self.job_lineEdit, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.nation_lineEdit = QtGui.QLineEdit(self.widget)
        self.nation_lineEdit.setObjectName(_fromUtf8("nation_lineEdit"))
        self.gridLayout.addWidget(self.nation_lineEdit, 1, 3, 1, 1)
        self.widget1 = QtGui.QWidget(self.splitter)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.widget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.address_lineEdit = QtGui.QLineEdit(self.widget1)
        self.address_lineEdit.setObjectName(_fromUtf8("address_lineEdit"))
        self.gridLayout_2.addWidget(self.address_lineEdit, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.widget1)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.label.setBuddy(self.name_lineEdit)
        self.label_5.setBuddy(self.comboBox)
        self.label_2.setBuddy(self.job_lineEdit)
        self.label_3.setBuddy(self.nation_lineEdit)
        self.label_4.setBuddy(self.address_lineEdit)
        self.label_6.setBuddy(self.comboBox_2)

        self.retranslateUi(PatientInfoDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PatientInfoDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PatientInfoDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PatientInfoDialog)
        PatientInfoDialog.setTabOrder(self.tabWidget, self.name_lineEdit)
        PatientInfoDialog.setTabOrder(self.name_lineEdit, self.comboBox)
        PatientInfoDialog.setTabOrder(self.comboBox, self.job_lineEdit)
        PatientInfoDialog.setTabOrder(self.job_lineEdit, self.nation_lineEdit)
        PatientInfoDialog.setTabOrder(self.nation_lineEdit, self.address_lineEdit)
        PatientInfoDialog.setTabOrder(self.address_lineEdit, self.comboBox_2)
        PatientInfoDialog.setTabOrder(self.comboBox_2, self.buttonBox)

    def retranslateUi(self, PatientInfoDialog):
        PatientInfoDialog.setWindowTitle(_translate("PatientInfoDialog", "患者信息", None))
        self.label.setText(_translate("PatientInfoDialog", "姓名", None))
        self.label_5.setText(_translate("PatientInfoDialog", "性别", None))
        self.comboBox.setItemText(0, _translate("PatientInfoDialog", "男", None))
        self.comboBox.setItemText(1, _translate("PatientInfoDialog", "女", None))
        self.label_2.setText(_translate("PatientInfoDialog", "职业", None))
        self.label_3.setText(_translate("PatientInfoDialog", "民族", None))
        self.label_4.setText(_translate("PatientInfoDialog", "家庭住址", None))
        self.label_6.setText(_translate("PatientInfoDialog", "文化程度", None))
        self.comboBox_2.setItemText(0, _translate("PatientInfoDialog", "大学以上", None))
        self.comboBox_2.setItemText(1, _translate("PatientInfoDialog", "大学", None))
        self.comboBox_2.setItemText(2, _translate("PatientInfoDialog", "高中", None))
        self.comboBox_2.setItemText(3, _translate("PatientInfoDialog", "初中", None))
        self.comboBox_2.setItemText(4, _translate("PatientInfoDialog", "小学", None))
        self.comboBox_2.setItemText(5, _translate("PatientInfoDialog", "文盲或半文盲", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PatientInfoDialog", "个人信息", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("PatientInfoDialog", "既往史", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("PatientInfoDialog", "就诊信息", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("PatientInfoDialog", "影响查看结果", None))

