# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DesignWindow.ui'
#
# Created: Tue Oct 08 16:20:16 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PatientInfoDialog(object):
    def setupUi(self, PatientInfoDialog):
        PatientInfoDialog.setObjectName(_fromUtf8("PatientInfoDialog"))
        PatientInfoDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        PatientInfoDialog.resize(688, 480)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        PatientInfoDialog.setFont(font)
        PatientInfoDialog.setAcceptDrops(False)
        self.tabWidget = QtGui.QTabWidget(PatientInfoDialog)
        self.tabWidget.setGeometry(QtCore.QRect(60, 30, 581, 381))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setGeometry(QtCore.QRect(80, 50, 431, 231))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.nameLineEdit = QtGui.QLineEdit(self.widget)
        self.nameLineEdit.setObjectName(_fromUtf8("nameLineEdit"))
        self.gridLayout.addWidget(self.nameLineEdit, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.sexComboBox = QtGui.QComboBox(self.widget)
        self.sexComboBox.setObjectName(_fromUtf8("sexComboBox"))
        self.sexComboBox.addItem(_fromUtf8(""))
        self.sexComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.sexComboBox, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.jobLineEdit = QtGui.QLineEdit(self.widget)
        self.jobLineEdit.setObjectName(_fromUtf8("jobLineEdit"))
        self.gridLayout.addWidget(self.jobLineEdit, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.nationLineEdit = QtGui.QLineEdit(self.widget)
        self.nationLineEdit.setObjectName(_fromUtf8("nationLineEdit"))
        self.gridLayout.addWidget(self.nationLineEdit, 1, 3, 1, 1)
        self.widget1 = QtGui.QWidget(self.splitter)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.widget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.addressLineEdit = QtGui.QLineEdit(self.widget1)
        self.addressLineEdit.setObjectName(_fromUtf8("addressLineEdit"))
        self.gridLayout_2.addWidget(self.addressLineEdit, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.degreeComboBox = QtGui.QComboBox(self.widget1)
        self.degreeComboBox.setObjectName(_fromUtf8("degreeComboBox"))
        self.degreeComboBox.addItem(_fromUtf8(""))
        self.degreeComboBox.addItem(_fromUtf8(""))
        self.degreeComboBox.addItem(_fromUtf8(""))
        self.degreeComboBox.addItem(_fromUtf8(""))
        self.degreeComboBox.addItem(_fromUtf8(""))
        self.degreeComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.degreeComboBox, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.acceptButton = QtGui.QPushButton(PatientInfoDialog)
        self.acceptButton.setGeometry(QtCore.QRect(466, 420, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.acceptButton.setFont(font)
        self.acceptButton.setObjectName(_fromUtf8("acceptButton"))
        self.cancelButton = QtGui.QPushButton(PatientInfoDialog)
        self.cancelButton.setGeometry(QtCore.QRect(560, 420, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.label.setBuddy(self.nameLineEdit)
        self.label_5.setBuddy(self.sexComboBox)
        self.label_2.setBuddy(self.jobLineEdit)
        self.label_3.setBuddy(self.nationLineEdit)
        self.label_4.setBuddy(self.addressLineEdit)
        self.label_6.setBuddy(self.degreeComboBox)

        self.retranslateUi(PatientInfoDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL(_fromUtf8("clicked()")), PatientInfoDialog.reject)
        QtCore.QObject.connect(self.acceptButton, QtCore.SIGNAL(_fromUtf8("clicked()")), PatientInfoDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(PatientInfoDialog)
        PatientInfoDialog.setTabOrder(self.tabWidget, self.nameLineEdit)
        PatientInfoDialog.setTabOrder(self.nameLineEdit, self.sexComboBox)
        PatientInfoDialog.setTabOrder(self.sexComboBox, self.jobLineEdit)
        PatientInfoDialog.setTabOrder(self.jobLineEdit, self.nationLineEdit)
        PatientInfoDialog.setTabOrder(self.nationLineEdit, self.addressLineEdit)
        PatientInfoDialog.setTabOrder(self.addressLineEdit, self.degreeComboBox)

    def retranslateUi(self, PatientInfoDialog):
        PatientInfoDialog.setWindowTitle(_translate("PatientInfoDialog", "患者信息", None))
        self.label.setText(_translate("PatientInfoDialog", "姓名", None))
        self.label_5.setText(_translate("PatientInfoDialog", "性别", None))
        self.sexComboBox.setItemText(0, _translate("PatientInfoDialog", "男", None))
        self.sexComboBox.setItemText(1, _translate("PatientInfoDialog", "女", None))
        self.label_2.setText(_translate("PatientInfoDialog", "职业", None))
        self.label_3.setText(_translate("PatientInfoDialog", "民族", None))
        self.label_4.setText(_translate("PatientInfoDialog", "家庭住址", None))
        self.label_6.setText(_translate("PatientInfoDialog", "文化程度", None))
        self.degreeComboBox.setItemText(0, _translate("PatientInfoDialog", "大学以上", None))
        self.degreeComboBox.setItemText(1, _translate("PatientInfoDialog", "大学", None))
        self.degreeComboBox.setItemText(2, _translate("PatientInfoDialog", "高中", None))
        self.degreeComboBox.setItemText(3, _translate("PatientInfoDialog", "初中", None))
        self.degreeComboBox.setItemText(4, _translate("PatientInfoDialog", "小学", None))
        self.degreeComboBox.setItemText(5, _translate("PatientInfoDialog", "文盲或半文盲", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PatientInfoDialog", "个人信息", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("PatientInfoDialog", "既往史", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("PatientInfoDialog", "就诊信息", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("PatientInfoDialog", "影响查看结果", None))
        self.acceptButton.setText(_translate("PatientInfoDialog", "确定", None))
        self.cancelButton.setText(_translate("PatientInfoDialog", "取消", None))

